// AgentCreatorAgent.kts — CORTEX Wizard
// Interactive agent creator. Driven by the CommandBridge:
//   - Writes questions to logs/wizard/<sessionId>.log  (TUI reads via LOG panel)
//   - Reads answers from commands/wizard/<ts>.response (TUI writes via command bar)
// Args: [jobsDir] [sessionId]

import java.io.File
import java.nio.file.*
import java.nio.file.StandardWatchEventKinds.*
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import java.util.concurrent.TimeUnit

val home      = System.getProperty("user.home")
val jobsDir   = File(args.getOrNull(0) ?: "$home/.koupper/jobs")
val sessionId = args.getOrNull(1) ?: "wizard-${System.currentTimeMillis()}"

val agentsDir   = File(home, ".koupper/agents").also { it.mkdirs() }
val wizardInDir = File(jobsDir, "commands/wizard").also { it.mkdirs() }
val logDir      = File(jobsDir, "logs/wizard").also { it.mkdirs() }
val logFile     = File(logDir, "$sessionId.log")
val queueDir    = File(jobsDir, "wizard").also { it.mkdirs() }
val procFile    = File(queueDir, "$sessionId.json.processing")

logFile.writeText("")

fun ts()             = LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"))
fun log(msg: String) = logFile.appendText("[${ts()}] $msg\n")
fun ask(msg: String) = logFile.appendText("[${ts()}] [?] $msg\n")

// Create job entry in .processing state so monitor shows it immediately
procFile.writeText("""{"id":"$sessionId","fileName":"AgentCreatorAgent","functionName":"run","scriptPath":"agents/AgentCreatorAgent.kts","sourceType":"script"}""")

// ── State machine ─────────────────────────────────────────────────────────────

enum class Step { NAME, ROLE, OBJECTIVE, DONE }
var step = Step.NAME
val draft = mutableMapOf<String, String>()

fun nextQuestion() {
    when (step) {
        Step.NAME      -> ask("What is the agent name? (e.g. DataSyncAgent)")
        Step.ROLE      -> ask("What is the agent role / specialty?")
        Step.OBJECTIVE -> ask("What is the agent objective / goal?")
        Step.DONE      -> {}
    }
}

fun processAnswer(answer: String) {
    val trimmed = answer.trim()
    when (step) {
        Step.NAME -> {
            val name = trimmed.replace(" ", "").let { if (it.endsWith("Agent")) it else "${it}Agent" }
            draft["name"] = name
            log("  ✓ Name      : $name")
            step = Step.ROLE
            nextQuestion()
        }
        Step.ROLE -> {
            draft["role"] = trimmed
            log("  ✓ Role      : $trimmed")
            step = Step.OBJECTIVE
            nextQuestion()
        }
        Step.OBJECTIVE -> {
            draft["objective"] = trimmed
            log("  ✓ Objective : $trimmed")
            step = Step.DONE
            generateAgent()
        }
        Step.DONE -> {}
    }
}

fun generateAgent() {
    val name      = draft["name"]      ?: "UnnamedAgent"
    val role      = draft["role"]      ?: "General purpose"
    val objective = draft["objective"] ?: "Execute tasks"
    val className = name.replaceFirstChar { it.uppercaseChar() }

    // Save draft metadata
    val draftFile = File(agentsDir, "draft_$name.json")
    draftFile.writeText("""
{
  "name": "$name",
  "role": "$role",
  "objective": "$objective",
  "createdAt": "${ts()}"
}
""".trimIndent())

    // Generate .kts scaffold
    val agentFile = File(agentsDir, "$name.kts")
    agentFile.writeText("""
// $name.kts
// Role      : $role
// Objective : $objective
// Generated by CORTEX WIZARD — ${ts()}

import java.io.File
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

val home    = System.getProperty("user.home")
val jobsDir = File(args.firstOrNull() ?: "${'$'}home/.koupper/jobs")
val jobId   = args.getOrNull(1) ?: "$name-${'$'}{System.currentTimeMillis()}"

val logDir  = File(jobsDir, "logs/default").also { it.mkdirs() }
val logFile = File(logDir, "${'$'}jobId.log")
fun ts()             = LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"))
fun log(msg: String) = logFile.appendText("[${"\${ts()}"}] \$msg\n")

// ── $name logic ───────────────────────────────────────────────────────────────
// TODO: Implement agent behavior
// Role:      $role
// Objective: $objective

log("$name started")
log("Role: $role")
log("Objective: $objective")
log("$name completed — READY")
""".trimIndent())

    log("")
    log("┌─────────────────────────────────────┐")
    log("│   AGENT READY FOR DEPLOYMENT        │")
    log("└─────────────────────────────────────┘")
    log("  NAME       : $name")
    log("  ROLE       : $role")
    log("  OBJECTIVE  : $objective")
    log("  FILE       : ~/.koupper/agents/$name.kts")
    log("  DRAFT      : ~/.koupper/agents/draft_$name.json")
    log("")
    log("  Run: koupper run ~/.koupper/agents/$name.kts")
    log("")
    log("  Press ESC to return to watch mode.")

    // Mark job done
    Thread.sleep(300)
    procFile.delete()
}

// ── Watch for wizard responses ────────────────────────────────────────────────

// Drain any stale response files from before this session
wizardInDir.listFiles { f -> f.name.endsWith(".response") }?.forEach { it.delete() }

log("┌─────────────────────────────────────┐")
log("│   CORTEX WIZARD — AGENT CREATOR     │")
log("└─────────────────────────────────────┘")
log("  Session: $sessionId")
log("  Type your answers in the command bar.")
log("  Press ESC to cancel at any time.")
log("")
nextQuestion()

val ws       = FileSystems.getDefault().newWatchService()
val deadline = System.currentTimeMillis() + 10 * 60 * 1000L  // 10-min timeout

wizardInDir.toPath().register(ws, ENTRY_CREATE)

while (step != Step.DONE && System.currentTimeMillis() < deadline) {
    val key = ws.poll(500, TimeUnit.MILLISECONDS) ?: continue

    for (ev in key.pollEvents()) {
        if (ev.kind() == OVERFLOW) continue
        @Suppress("UNCHECKED_CAST")
        val fname = (ev as WatchEvent<Path>).context().fileName.toString()
        if (!fname.endsWith(".response")) continue

        val responseFile = File(wizardInDir, fname)
        val answer = runCatching { responseFile.readText().trim() }.getOrDefault("")
        responseFile.delete()

        if (answer.isNotEmpty() && step != Step.DONE) {
            processAnswer(answer)
        }
    }
    key.reset()
}

if (step != Step.DONE) {
    log("")
    log("[!] Session timed out or cancelled.")
    procFile.delete()
}

ws.close()
