// AgentCreatorAgent.kts — CORTEX Wizard
// Interactive agent creator driven by CommandBridgeProvider.
// Reads answers from commands/wizard/*.response files written by the TUI or web UI.

import com.koupper.container.app
import com.koupper.providers.commandbridge.CommandBridgeProvider
import com.koupper.shared.annotations.Export
import java.io.File
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

enum class WizardStep { NAME, ROLE, OBJECTIVE, DONE }

@Export
val setup: () -> Unit = {
    val home      = System.getProperty("user.home")!!
    val jobsDir   = File(System.getenv("CORTEX_JOBS_DIR") ?: "$home/.koupper/jobs")
    val sessionId = "wizard-${System.currentTimeMillis()}"

    val agentsDir   = File(home, ".koupper/agents").also { it.mkdirs() }
    val wizardInDir = File(jobsDir, "commands/wizard").also { it.mkdirs() }
    val logDir      = File(jobsDir, "logs/wizard").also { it.mkdirs() }
    val logFile     = File(logDir, "$sessionId.log")
    val queueDir    = File(jobsDir, "wizard").also { it.mkdirs() }
    val procFile    = File(queueDir, "$sessionId.json.processing")

    logFile.writeText("")

    fun ts()             = LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"))
    fun log(msg: String) = logFile.appendText("[${ts()}] $msg\n")
    fun ask(msg: String) = logFile.appendText("[${ts()}] [?] $msg\n")

    procFile.writeText("""{"id":"$sessionId","fileName":"AgentCreatorAgent","functionName":"setup","scriptPath":"agents/AgentCreatorAgent.kts","sourceType":"script"}""")

    // ── State machine ─────────────────────────────────────────────────────────

    var step = WizardStep.NAME
    val draft = mutableMapOf<String, String>()

    fun generateAgent() {
        val name      = draft["name"]      ?: "UnnamedAgent"
        val role      = draft["role"]      ?: "General purpose"
        val objective = draft["objective"] ?: "Execute tasks"

        // Split @Export so octopus annotation scanner doesn't find a second one here
        val exportLine = "@" + "Export"

        File(agentsDir, "draft_$name.json").writeText(
            """{"name":"$name","role":"$role","objective":"$objective","createdAt":"${ts()}"}"""
        )

        File(agentsDir, "$name.kts").writeText("""
// $name.kts
// Role      : $role
// Objective : $objective
// Generated by CORTEX WIZARD — ${ts()}

import com.koupper.shared.annotations.Export
import java.io.File
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

$exportLine
val setup: () -> Unit = {
    val home    = System.getProperty("user.home")!!
    val jobsDir = File(System.getenv("CORTEX_JOBS_DIR") ?: "${'$'}home/.koupper/jobs")
    val jobId   = "$name-${'$'}{System.currentTimeMillis()}"
    val logDir  = File(jobsDir, "logs/default").also { it.mkdirs() }
    val logFile = File(logDir, "${'$'}jobId.log")
    fun ts()             = LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"))
    fun log(msg: String) = logFile.appendText("[${'$'}{ts()}] ${'$'}msg\n")

    // TODO: Implement agent behavior
    // Role:      $role
    // Objective: $objective

    log("$name started")
    log("Role: $role")
    log("Objective: $objective")
    log("$name completed — READY")
}
""".trimIndent())

        log("")
        log("┌─────────────────────────────────────┐")
        log("│   AGENT READY FOR DEPLOYMENT        │")
        log("└─────────────────────────────────────┘")
        log("  NAME       : $name")
        log("  ROLE       : $role")
        log("  OBJECTIVE  : $objective")
        log("  FILE       : ~/.koupper/agents/$name.kts")
        log("")
        log("  Run: koupper run ~/.koupper/agents/$name.kts")

        step = WizardStep.DONE
        Thread.sleep(300)
        procFile.delete()
    }

    fun nextQuestion() {
        when (step) {
            WizardStep.NAME      -> ask("What is the agent name? (e.g. DataSyncAgent)")
            WizardStep.ROLE      -> ask("What is the agent role / specialty?")
            WizardStep.OBJECTIVE -> ask("What is the agent objective / goal?")
            WizardStep.DONE      -> {}
        }
    }

    fun processAnswer(answer: String) {
        when (step) {
            WizardStep.NAME -> {
                val name = answer.replace(" ", "").let { if (it.endsWith("Agent")) it else "${it}Agent" }
                draft["name"] = name
                log("  ✓ Name      : $name")
                step = WizardStep.ROLE
                nextQuestion()
            }
            WizardStep.ROLE -> {
                draft["role"] = answer
                log("  ✓ Role      : $answer")
                step = WizardStep.OBJECTIVE
                nextQuestion()
            }
            WizardStep.OBJECTIVE -> {
                draft["objective"] = answer
                log("  ✓ Objective : $answer")
                generateAgent()
            }
            WizardStep.DONE -> {}
        }
    }

    // ── Command loop ──────────────────────────────────────────────────────────

    log("┌─────────────────────────────────────┐")
    log("│   CORTEX WIZARD — AGENT CREATOR     │")
    log("└─────────────────────────────────────┘")
    log("  Type your answers in the command bar.")
    log("")
    nextQuestion()

    val bridge   = app.getInstance(CommandBridgeProvider::class)
    val deadline = System.currentTimeMillis() + 10 * 60 * 1000L

    bridge.watch(wizardInDir).drain()

    while (step != WizardStep.DONE && System.currentTimeMillis() < deadline) {
        val answer = bridge.nextCommand() ?: continue
        if (answer.isNotBlank()) processAnswer(answer)
    }

    if (step != WizardStep.DONE) {
        log("")
        log("[!] Session timed out or cancelled.")
        procFile.delete()
    }

    bridge.close()
}
