import com.koupper.container.context
import com.koupper.shared.annotations.Export
import java.io.File
import java.util.concurrent.TimeUnit

data class Input(
    val baseBranch: String = "develop",
    val headBranch: String? = null,
    val title: String? = null,
    val body: String? = null,
    val draft: Boolean = false,
    val pushBranch: Boolean = true,
    val commandTimeoutSeconds: Long = 120,
    val commandRetries: Int = 1,
    val retryDelaySeconds: Long = 2
)

data class CommandResult(
    val command: String,
    val exitCode: Int,
    val output: String
)

private fun runCommand(
    args: List<String>,
    cwd: File,
    timeoutSeconds: Long,
    retries: Int,
    retryDelaySeconds: Long
): CommandResult {
    var attempt = 0
    var last = CommandResult(command = args.joinToString(" "), exitCode = 1, output = "")

    while (attempt <= retries) {
        val process = ProcessBuilder(args)
            .directory(cwd)
            .redirectErrorStream(true)
            .start()

        val completed = process.waitFor(timeoutSeconds, TimeUnit.SECONDS)
        if (!completed) {
            process.destroyForcibly()
            last = CommandResult(args.joinToString(" "), 124, "command timed out after ${timeoutSeconds}s")
        } else {
            val output = process.inputStream.bufferedReader().readText().trim()
            last = CommandResult(args.joinToString(" "), process.exitValue(), output)
        }

        if (last.exitCode == 0 || attempt == retries) return last

        Thread.sleep(retryDelaySeconds * 1000)
        attempt++
    }

    return last
}

private fun ensureOk(result: CommandResult, step: String) {
    if (result.exitCode != 0) {
        error("$step failed (${result.command}): ${result.output}")
    }
}

private fun existingPrUrl(output: String): String? {
    if (output.isBlank()) return null
    if (!output.contains("already exists", ignoreCase = true)) return null
    return output.lines().map { it.trim() }.firstOrNull { it.startsWith("http") }
}

private fun resolveCurrentBranch(cwd: File, input: Input): String {
    val current = runCommand(
        listOf("git", "branch", "--show-current"),
        cwd,
        input.commandTimeoutSeconds,
        input.commandRetries,
        input.retryDelaySeconds
    )
    ensureOk(current, "resolve current branch")
    return current.output.ifBlank { error("unable to resolve current branch") }
}

private fun autoBody(cwd: File, base: String, head: String, input: Input): String {
    val commits = runCommand(
        listOf("git", "log", "--oneline", "$base..$head"),
        cwd,
        input.commandTimeoutSeconds,
        input.commandRetries,
        input.retryDelaySeconds
    )
    ensureOk(commits, "collect commits for PR body")
    val bulletLines = commits.output
        .lines()
        .map { it.trim() }
        .filter { it.isNotBlank() }
        .take(8)
        .joinToString("\n") { "- $it" }

    val diffStat = runCommand(
        listOf("git", "diff", "--stat", "$base..$head"),
        cwd,
        input.commandTimeoutSeconds,
        input.commandRetries,
        input.retryDelaySeconds
    )
    ensureOk(diffStat, "collect diff stat for PR body")

    return buildString {
        appendLine("## Summary")
        if (bulletLines.isBlank()) {
            appendLine("- Automated PR generated by scripts/release/pr-create.kts")
        } else {
            appendLine(bulletLines)
        }
        appendLine()
        appendLine("## Diff")
        appendLine("```")
        appendLine(diffStat.output.ifBlank { "No file changes detected." })
        appendLine("```")
    }.trim()
}

@Export
val setup: (Input) -> Map<String, Any?> = { input ->
    val cwd = File(context ?: ".").absoluteFile
    val head = input.headBranch?.takeIf { it.isNotBlank() } ?: resolveCurrentBranch(cwd, input)

    if (input.pushBranch) {
        ensureOk(
            runCommand(
                listOf("git", "push", "-u", "origin", head),
                cwd,
                input.commandTimeoutSeconds,
                input.commandRetries,
                input.retryDelaySeconds
            ),
            "push feature branch"
        )
    }

    val computedTitle = input.title?.takeIf { it.isNotBlank() } ?: run {
        val latest = runCommand(
            listOf("git", "log", "-1", "--format=%s"),
            cwd,
            input.commandTimeoutSeconds,
            input.commandRetries,
            input.retryDelaySeconds
        )
        ensureOk(latest, "resolve default PR title")
        latest.output.ifBlank { "chore: update branch $head" }
    }

    val computedBody = input.body?.takeIf { it.isNotBlank() } ?: autoBody(cwd, input.baseBranch, head, input)

    val createArgs = mutableListOf(
        "gh", "pr", "create",
        "--base", input.baseBranch,
        "--head", head,
        "--title", computedTitle,
        "--body", computedBody
    )
    if (input.draft) createArgs += "--draft"

    val created = runCommand(
        createArgs,
        cwd,
        input.commandTimeoutSeconds,
        input.commandRetries,
        input.retryDelaySeconds
    )

    val existingUrl = if (created.exitCode != 0) existingPrUrl(created.output) else null
    if (created.exitCode != 0 && existingUrl == null) {
        ensureOk(created, "create PR")
    }

    val prUrl = existingUrl ?: created.output.lines().firstOrNull { it.startsWith("http") }
        ?: run {
            val fallback = runCommand(
                listOf("gh", "pr", "view", "--json", "url", "--jq", ".url"),
                cwd,
                input.commandTimeoutSeconds,
                input.commandRetries,
                input.retryDelaySeconds
            )
            ensureOk(fallback, "resolve PR URL")
            fallback.output
        }

    mapOf(
        "ok" to true,
        "baseBranch" to input.baseBranch,
        "headBranch" to head,
        "title" to computedTitle,
        "url" to prUrl,
        "existing" to (existingUrl != null)
    )
}
