plugins {
    id 'application'
    id 'org.jetbrains.kotlin.jvm' version '2.0.21'
}

repositories {
    mavenCentral()
    mavenLocal()
    flatDir {
        dirs 'libs'
    }
}

def kotlinVersion = '2.0.21'
def kotlinTestVersion = '2.0.21'

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    // Koupper compile API (from mavenLocal after install / upgrade)
    implementation("com.koupper:octopus-api:7.2.1")
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0"

    // HTTP Engine (Required for RuntimeRouterProvider)
    implementation "org.glassfish.grizzly:grizzly-http-server:4.0.2"

    // Utilities
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin:2.17.2"
    implementation "com.beust:klaxon:5.6"

    testImplementation "org.jetbrains.kotlin:kotlin-test:$kotlinTestVersion"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit5:$kotlinTestVersion"

    implementation 'com.amazonaws:aws-lambda-java-core:1.2.3'
    implementation 'com.amazonaws:aws-lambda-java-events:3.14.0'
    runtimeOnly 'com.amazonaws:aws-lambda-java-log4j2:1.6.0'

    implementation "jakarta.servlet:jakarta.servlet-api:5.0.0"
}

task copyDependencies(type: Copy) {
    into("$buildDir/libs")
    from(configurations.runtimeClasspath) {
        into 'lib'
    }
}

application {
    mainClass.set("server.SetupKt")
}

kotlin {
    jvmToolchain(17)
}

tasks.named('test') {
    useJUnitPlatform()
}

startScripts.dependsOn(copyDependencies)

version = '0.0.0'
